#:kivy 2.1.0
UIBox:

<UIBox>:
    canvas:
        Rectangle:
            pos: self.center_x / 2, self.center_y / 2
            size: 10, self.height / 2
        Rectangle:
            pos: self.center_x * 3/2, self.center_y / 2
            size: 10, self.height / 2
        Rectangle:
            pos: self.center_x / 2, self.center_y / 2
            size: 25, 10
        Rectangle:
            pos: self.center_x *3 / 2 -15, self.center_y / 2
            size: 25, 10
        Rectangle:
            pos: self.center_x / 2 , self.center_y * 3 / 2
            size: 25, 10
        Rectangle:
            pos: self.center_x *3 / 2 -15, self.center_y* 3 / 2
            size: 25, 10
        
    Button:
        pos: 350, 20
        text: "Başlat"
        on_press: root.on_button1_click()

    Label:
        id:label_1
        text: "Gyro"
        halign: "left"
        valign: "top"
        font_size: 32
